export enum Role {
  USER = "USER",
  ORGANIZATION = "ORGANIZATION",
  ADMIN = "ADMIN",
}

export enum NotificationType {
  // System
  SYSTEM = "SYSTEM",

  // Order
  ORDER_CREATED = "ORDER_CREATED",
  ORDER_CONFIRMED = "ORDER_CONFIRMED",
  ORDER_SHIPPED = "ORDER_SHIPPED",
  ORDER_DELIVERED = "ORDER_DELIVERED",
  ORDER_CANCELLED = "ORDER_CANCELLED",

  // Payment
  PAYMENT_SUCCESS = "PAYMENT_SUCCESS",
  PAYMENT_FAILED = "PAYMENT_FAILED",

  // Social
  USER_FOLLOWED = "USER_FOLLOWED",
  POST_LIKED = "POST_LIKED",
  POST_COMMENTED = "POST_COMMENTED",
  COMMENT_REPLIED = "COMMENT_REPLIED",

  // Promotion
  PROMOTION = "PROMOTION",

  // Gig Platform
  JOB_APPLICATION_RECEIVED = "JOB_APPLICATION_RECEIVED",
  JOB_APPLICATION_ACCEPTED = "JOB_APPLICATION_ACCEPTED",
  JOB_APPLICATION_REJECTED = "JOB_APPLICATION_REJECTED",
  JOB_COMPLETED = "JOB_COMPLETED",
  JOB_CANCELLED = "JOB_CANCELLED",
  JOB_CHECKED_IN = "JOB_CHECKED_IN",
  APPLICATION_CANCELLED = "APPLICATION_CANCELLED",
  REVIEW_RECEIVED = "REVIEW_RECEIVED",
  PAYMENT_CONFIRMED = "PAYMENT_CONFIRMED",
  PAYMENT_DISPUTED = "PAYMENT_DISPUTED",
  DISPUTE_RESOLVED = "DISPUTE_RESOLVED",
}

export enum ReferenceType {
  ORDER = "ORDER",
  PAYMENT = "PAYMENT",
  USER = "USER",
  POST = "POST",
  COMMENT = "COMMENT",
  PRODUCT = "PRODUCT",
  PROMOTION = "PROMOTION",
  JOB = "JOB",
  JOB_APPLICATION = "JOB_APPLICATION",
  REVIEW = "REVIEW",
  DISPUTE = "DISPUTE",
}

export enum JobStatus {
  OPEN = "OPEN",
  CLOSED = "CLOSED",
  CANCELLED = "CANCELLED",
}

export enum ApplicationStatus {
  PENDING = "PENDING",
  ACCEPTED = "ACCEPTED",
  REJECTED = "REJECTED",
  CANCELLED = "CANCELLED",
}

export enum AssignmentStatus {
  ASSIGNED = "ASSIGNED",
  IN_PROGRESS = "IN_PROGRESS",
  COMPLETED = "COMPLETED",
  CANCELLED = "CANCELLED",
}

export enum ReportStatus {
  PENDING = "PENDING",
  REVIEWED = "REVIEWED",
  RESOLVED = "RESOLVED",
  DISMISSED = "DISMISSED",
}

export enum PaymentStatus {
  PENDING = "PENDING",
  PAYMENT_CONFIRMED = "PAYMENT_CONFIRMED",
  DISPUTED = "DISPUTED",
}

export enum PaymentType {
  FINAL_PAYMENT = "FINAL_PAYMENT",
}

export enum DisputeStatus {
  OPEN = "OPEN",
  UNDER_REVIEW = "UNDER_REVIEW",
  RESOLVED = "RESOLVED",
  DISMISSED = "DISMISSED",
}

export enum EmployerBadge {
  NONE = "NONE",
  VERIFIED = "VERIFIED",
  TRUSTED = "TRUSTED",
  TOP = "TOP",
}

export enum VerificationLevel {
  NONE = "NONE",
  BASIC = "BASIC",
  BUSINESS = "BUSINESS",
}

export enum JobType {
  GIG = "GIG",
  PART_TIME = "PART_TIME",
  ONLINE = "ONLINE",
}
